name: "Compile mermaid"

on:
  push:
    paths:
      - "**/*.mermaid"
      - "**/*.mmd"
      - "**/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get input files with changes
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e 'input/.*\.md$' -e 'input/.*\.*mmd$' -e 'input/.*\.mermaid$' | xargs)"
      - name: Output input files with changes
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Compile mermaid files
        uses: neenjaw/compile-mermaid-markdown-action@master
        if: startsWith(steps.getfile.outputs.files, 'input/')
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: "output"
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1
      - name: Commit
        run: |
          if [[ $(git diff --exit-code) ]]; then
            git config --local user.email "leodidonato@gmail.com"
            git config --local user.name "Leonardo Di Donato"
            git add -A && git commit -m "new: diagrams"
          fi
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
